// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_city_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQKg"; // <GPGSID>
        public const string achievement_jobs_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQMQ"; // <GPGSID>
        public const string achievement_jobs_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQJA"; // <GPGSID>
        public const string achievement_animals_all_normal_levels = "CgkI6Mme_O4GEAIQDg"; // <GPGSID>
        public const string achievement_animals_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQNQ"; // <GPGSID>
        public const string achievement_school_all_normal_levels = "CgkI6Mme_O4GEAIQGA"; // <GPGSID>
        public const string achievement_city_all_normal_levels = "CgkI6Mme_O4GEAIQEA"; // <GPGSID>
        public const string achievement_everyday_life_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQIw"; // <GPGSID>
        public const string achievement_food_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQLg"; // <GPGSID>
        public const string achievement_human_body_all_normal_levels = "CgkI6Mme_O4GEAIQDw"; // <GPGSID>
        public const string leaderboard_sport = "CgkI6Mme_O4GEAIQCw"; // <GPGSID>
        public const string achievement_food_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQOw"; // <GPGSID>
        public const string achievement_countries_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQLA"; // <GPGSID>
        public const string achievement_all_normal_levels_in_every_category = "CgkI6Mme_O4GEAIQQg"; // <GPGSID>
        public const string achievement_everyday_life_all_normal_levels = "CgkI6Mme_O4GEAIQFg"; // <GPGSID>
        public const string achievement_travel_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQJw"; // <GPGSID>
        public const string achievement_travel_all_normal_levels = "CgkI6Mme_O4GEAIQGg"; // <GPGSID>
        public const string leaderboard_countries = "CgkI6Mme_O4GEAIQBA"; // <GPGSID>
        public const string achievement_countries_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQHw"; // <GPGSID>
        public const string leaderboard_human_body = "CgkI6Mme_O4GEAIQAg"; // <GPGSID>
        public const string achievement_countries_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQOQ"; // <GPGSID>
        public const string achievement_school_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQMg"; // <GPGSID>
        public const string achievement_ecology_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQLQ"; // <GPGSID>
        public const string achievement_clothes_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQKw"; // <GPGSID>
        public const string achievement_city_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQNw"; // <GPGSID>
        public const string achievement_house_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQLw"; // <GPGSID>
        public const string leaderboard_clothes = "CgkI6Mme_O4GEAIQAw"; // <GPGSID>
        public const string leaderboard_jobs = "CgkI6Mme_O4GEAIQCQ"; // <GPGSID>
        public const string achievement_clothes_all_normal_levels = "CgkI6Mme_O4GEAIQEQ"; // <GPGSID>
        public const string achievement_countries_all_normal_levels = "CgkI6Mme_O4GEAIQEg"; // <GPGSID>
        public const string achievement_sport_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQJg"; // <GPGSID>
        public const string achievement_house_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQIg"; // <GPGSID>
        public const string achievement_sport_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQMw"; // <GPGSID>
        public const string leaderboard_animals = "CgkI6Mme_O4GEAIQAQ"; // <GPGSID>
        public const string achievement_house_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQPA"; // <GPGSID>
        public const string achievement_clothes_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQHg"; // <GPGSID>
        public const string achievement_school_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQJQ"; // <GPGSID>
        public const string achievement_jobs_all_normal_levels = "CgkI6Mme_O4GEAIQFw"; // <GPGSID>
        public const string achievement_city_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQHQ"; // <GPGSID>
        public const string achievement_travel_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQQQ"; // <GPGSID>
        public const string leaderboard_ecology = "CgkI6Mme_O4GEAIQBQ"; // <GPGSID>
        public const string achievement_school_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQPw"; // <GPGSID>
        public const string achievement_everyday_life_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQMA"; // <GPGSID>
        public const string achievement_sport_all_normal_levels = "CgkI6Mme_O4GEAIQGQ"; // <GPGSID>
        public const string leaderboard_city = "CgkI6Mme_O4GEAIQDQ"; // <GPGSID>
        public const string achievement_ecology_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQIA"; // <GPGSID>
        public const string achievement_house_all_normal_levels = "CgkI6Mme_O4GEAIQFQ"; // <GPGSID>
        public const string achievement_animals_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQKA"; // <GPGSID>
        public const string achievement_ecology_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQOg"; // <GPGSID>
        public const string achievement_all_levels_in_every_category_with_1_star_minimum = "CgkI6Mme_O4GEAIQQw"; // <GPGSID>
        public const string achievement_human_body_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQNg"; // <GPGSID>
        public const string achievement_animals_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQGw"; // <GPGSID>
        public const string achievement_all_levels_in_every_category_with_2_stars_minimum = "CgkI6Mme_O4GEAIQRA"; // <GPGSID>
        public const string leaderboard_everyday_life = "CgkI6Mme_O4GEAIQCA"; // <GPGSID>
        public const string achievement_clothes_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQOA"; // <GPGSID>
        public const string achievement_everyday_life_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQPQ"; // <GPGSID>
        public const string achievement_sport_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQQA"; // <GPGSID>
        public const string leaderboard_school = "CgkI6Mme_O4GEAIQCg"; // <GPGSID>
        public const string achievement_travel_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQNA"; // <GPGSID>
        public const string achievement_food_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQIQ"; // <GPGSID>
        public const string achievement_human_body_all_levels_with_1_star_minimum = "CgkI6Mme_O4GEAIQHA"; // <GPGSID>
        public const string achievement_all_levels_in_every_category_with_3_stars_the_ultimate_achievement = "CgkI6Mme_O4GEAIQRQ"; // <GPGSID>
        public const string leaderboard_travel = "CgkI6Mme_O4GEAIQDA"; // <GPGSID>
        public const string achievement_food_all_normal_levels = "CgkI6Mme_O4GEAIQFA"; // <GPGSID>
        public const string leaderboard_house = "CgkI6Mme_O4GEAIQBw"; // <GPGSID>
        public const string achievement_human_body_all_levels_with_2_stars_minimum = "CgkI6Mme_O4GEAIQKQ"; // <GPGSID>
        public const string achievement_ecology_all_normal_levels = "CgkI6Mme_O4GEAIQEw"; // <GPGSID>
        public const string leaderboard_food = "CgkI6Mme_O4GEAIQBg"; // <GPGSID>
        public const string achievement_jobs_all_levels_with_3_stars = "CgkI6Mme_O4GEAIQPg"; // <GPGSID>

}

